const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",

  ADD_NEW_COMMENT_START: "ADD_NEW_COMMENT_START",
  FETCH_COMMENTS_START: "FETCH_COMMENTS_START",
  DELETE_COMMENT_START: "DELETE_COMMENT_START",
  SET_COMMENTS: "SET_COMMENTS",
  REJECT_COMMENT_START: "REJECT_COMMENT_START",
  GET_UNAPPROVED_COMMENTS: "GET_UNAPPROVED_COMMENTS",
  APPROVE_COMMENT_START: "APPROVE_COMMENT_START",
  DISCOUNT_PRODUCT_START: "DISCOUNT_PRODUCT_START"
}

export default productsTypes
